# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D6D2DD
background         #070607
cursor             #D6D2DD

active_tab_foreground     #070607
active_tab_background     #D6D2DD
inactive_tab_foreground   #D6D2DD
inactive_tab_background   #070607

active_border_color   #D6D2DD
inactive_border_color #070607
bell_border_color     #080405

color0      #343333
color1		#080405
color2		#080405
color3		#37313E
color4		#43344D
color5		#605970
color6		#665E77
color7		#BBB6C7
color8		#837F8B
color9		#0B0507
color10		#0B0507
color11		#4A4153
color12		#594567
color13		#817696
color14		#897E9F
color15		#BBB6C7
