# ~/.config/kitty/kitty.conf

# Font settings
font_family      Fira Code Retina
font_size        13.5
line_height      1.2

# Window settings
background #121418
foreground #dddddd
cursor #dddddd
enable_audio_bell no

# Colors
color0          #282c34
color1          #e06c75
color2          #98c379
color3          #e5c07b
color4          #61afef
color5          #c678dd
color6          #56b6c2
color7          #abb2bf
color8          #5c6370
color9          #be5046
color10         #98c379
color11         #d19a66
color12         #61afef
color13         #c678dd
color14         #56b6c2
color15         #ffffff

# Other settings
cursor_shape    block
scrollback_lines 10000
